name: http_cache
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Yoeri-z/http_cache

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  http: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
